Publish minutes of 2021-12-09 meeting
w3c/webextensions pull request #141
Opened 2021-12-09 17:45 UTC by Rob--W

Generated from https://docs.google.com/document/d/1QkwhEMtMS67JBUkl_WVPZ4lRSKoWcQNlLJSf_GwSXg8/edit using the tool and process from #105.

During this meeting we discussed or mentioned #134, #120, #93 and #118. Although added to the agenda, we did not have enough time to discuss #113 and #115.

2021-12-10 10:12 UTC, nifgraup commented
Was #133 not on the agenda?

2021-12-10 16:41 UTC, Rob--W commented
> Was #133 not on the agenda?

Apparently not. But we didn't have enough time to get through all points that were on the agenda.

But #133 is about functionality that's lost if background pages were to be replaced with a service worker with a limited lifetime.
That broader topic was covered extensively during the meeting, as part of issue #134, #120 and the "Random Q&A related to MV3".

Note: if you'd like to discuss the specifics of #133, just post in #133; it's not necessary to wait for the video meetings to participate in the discussion.

2021-12-14 09:07 UTC, dotproto requested changes

2021-12-14 09:07 UTC, dotproto commented on _minutes/2021-12-09-wecg.md
> + * [rob] Firefox develops new features restricted to MV3,
@Rob--W, looks like we only got the first half of your thought. Do you recall what the second half was?

2021-12-14 09:07 UTC, dotproto commented on _minutes/2021-12-09-wecg.md
> + * [devlin] An issue with the implementation is that it's synchronous. [spoke to Chrome implementation details related to process responsibility and message passing]
```suggestion
 * [devlin] An issue with the implementation is that it's synchronous. [spoke to Chrome implementation details related to process responsibility, message passing between processes, challenges in supporting synchronous responses, and use cases that currently require synchronous responses]
```

I don't recall Devlin's comment with much specific detail, but I think this captures the essence of what he said a little more accurately.

2021-12-14 09:36 UTC, Rob--W commented
Thanks for the review @dotproto! I have updated the PR, the diff is at https://github.com/w3c/webextensions/compare/add3df59d4e9fd5c9f6cd2f454298319ad63a5f9..445963dd60096b64da4adf571b2d29b5961e970a

2021-12-16 07:12 UTC, dotproto approved these changes
Thanks for the updates, @Rob--W. I think we're good to go :)

2021-12-16 16:10 UTC, merged