Publish minutes of 2022-01-06 meeting
w3c/webextensions pull request #142
Opened 2022-01-06 18:09 UTC by Rob--W

Generated from https://docs.google.com/document/d/1QkwhEMtMS67JBUkl_WVPZ4lRSKoWcQNlLJSf_GwSXg8/edit using the tool and process from #105.

During this meeting we discussed or mentioned #134, #139 and #12. Although added to the agenda, we did not discuss #115 because @carlosjeurissen was not present to elaborate on the reason for adding it to the agenda again.
@dotproto started the meeting with a proposal of how he'd like to run the meeting, for which he'll file a new issue. He also elaborated on DOM-based use cases that started in [the last meeting](https://github.com/w3c/webextensions/blob/main/_minutes/2021-12-09-wecg.md) (part of #120).
@oliverdunk mentioned that he's working on an early proposal to access the keychain to support password managers. We may see a new issue filed if the proposal becomes more concrete.

2022-01-06 22:59 UTC, dotproto requested changes
I mostly tried to clarify my own statements, but also added a couple tweaks to others' comments to try to better represent the conversation as I recall it.

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> +   -- (possibly others?)
```suggestion
      - WebExtensions
      - (possibly others?)
```

Fix formatting on sub-list items. The current indentation is 3 spaces, so this suggestion also uses 3 spaces for the next level of sub-bullets.

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> +   To that end, my goal here is to share my tentative plan on how I plan to conduct myself as co-chair and to get initial feedback on the direction I'm planning to steer us.
```suggestion
      To that end, my goal here is to share my tentative plan on how I plan to conduct myself as co-chair and to get initial feedback on the direction I'm planning to steer us.
```

Indent an additional 3 spaces to make this paragraph a child of list item number 3.

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> + * [simeon] In the charter we wanted to start with the common base (e.g. manifest, localization). [_Notes that we are over time and should follow up on this topic later._]
```suggestion
 * [simeon] Agree that we should continue discussing Manifest V3 issues, but the problem is that this CG is chartered to work on a common base that spans manifest versions (e.g. manifest structure, localization, content scripts, etc.). The charter is meant to guide what we do and the chairs are responsible for pursuing that work. If we want to change our focus, it may be best to discuss modifying the charter. [_Notes that we are over time and should follow up on this topic later._]
```

Tried to embellish this comment based on my recollection of what I said.

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> +   * [simeon] A lot of what we've covered so far is independent of the manifest version.
```suggestion
   * [simeon] A lot of what we've covered so far is independent of the manifest version. We shouldn't be specifying MV2, but rather the common parts of the platform across all implementations.
```

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> + * [Rob] One of the items you mentioned was shepherding projects. Let's see if there's interest in that area before pushing it too hard. Being conscious of the time during synchronous meetings would
```suggestion
 * [rob] One of the items you mentioned was shepherding projects. Let's see if there's interest in that area before pushing it too hard. Being conscious of the time during synchronous meetings would be good to do regardless.
```

Normalize casing on speaker name

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> + * [simeon] Hadn't considered that, but would like to explore it more.
```suggestion
 * [simeon] Hadn't considered that, but would like to explore it more. Could you create an issue?
 ```

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> + * [simeon] Last meeting, Devlin and I tried to offer a proposal to address some DOM-based use cases. Unfortunately we didn't spend much time discussing that. To that end, the summary is that we are
```suggestion
 * [simeon] Last meeting I asked Devlin to attend in order to discuss a proposal we're preparing to address some background DOM-based use cases in Manifest V3. Unfortunately we didn't spend much time discussing that. To that end, the summary is that we are offering a counter-proposal/augmentation to the Limited Event pages proposal ([issue 134](https://github.com/w3c/webextensions/issues/134)). We're trying to modify the contract to make it more clear to developers when and how a background page can run.
```

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> + * [simeon] As I understand the Limited event page proposal is that one of the core assumptions is that the background page will be there as long as the extension does work.
```suggestion
 * [simeon] As I understand the limited event page proposal, one of the core assumptions is that the background page will be there as long as the extension does work. That's not a guarantee that Chrome can continue to make  given our engineering objectives.
```

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> + * [simeon] _(trying to answer but can't find the words)_. Rob, could you help with restating Google's position?
```suggestion
 * [simeon] _(trying to answer but can't find the words)_. Rob, we've discussed this a bit; could you try to reframe Chrome's concerns as you understand them?
```

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> + * [rob] Google wants (service) worker-first extensions, and in limited event pages the background would be on the main thread.
```suggestion
 * [rob] Google wants (service) worker-first extensions, and in limited event pages the background would be on the main thread.
 * [simeon] Chrome is also targeting constrained environments where, despite our fundamentally multi-process model, we need to be more aggressive about limiting concurrent processes.
```

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> + * [simeon] Without Carlos here I'm not sure what there is left to discuss, shelve it for  the next meeting.
```suggestion
 * [simeon] Without Carlos here I'm not sure what there is left to discuss. I suggest we shelve it for the next meeting.
```

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> + * [oliver] Haven't thought about that, was polling for interests at this point. Looking forward to chats on Matrix.
```suggestion
 * [oliver] Haven't thought about that, was polling for interests at this point. Looking forward to chats on Matrix.
 * [simeon] Very interested to see what you have in mind.
```

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> + * [simeon] From the extension design POV, an important consideration is that user script capabilities are not always available, and extensions need to account for this, e.g. show the user how to opt
```suggestion
 * [simeon] Sounds like a reasonable request for managed environments. From the extension design POV, an important consideration is that user script capabilities are not always available, and extensions need to account for this, e.g. show the user how to opt in.
```

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> + * [simeon] No design doc for user scripts yet, hoping to land the feature before MV2's deprecation.
```suggestion
 * [simeon] No design doc for user scripts yet. Planning to land the feature before Chrome's MV2 deprecation, but don't have anything more concrete to share at the moment.
```

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> + * [simeon] Big concern from our POV is that arbitrary code execution is a dangerous capability that most Chrome users don't understand. We want to offer this capability without putting most Chrome u
```suggestion
 * [simeon] Big concern from our POV is that arbitrary code execution is a dangerous capability that most Chrome users don't understand. We want to offer this capability without putting most Chrome users at risk. Other browsers focusing on power users may take a different approach to enable this capability.
```

2022-01-06 22:59 UTC, dotproto commented on _minutes/2022-01-06-wecg.md
> + * [krysztof] Having multiple layers of permissions / opts-in can cause confusion and cause users to incorrectly believe that they're protected. E.g. use case of content blocking extension: if a user
```suggestion
 * [krysztof] Having multiple layers of permissions / opts-in can cause confusion and cause users to incorrectly believe that they're protected. E.g. use case of content blocking extension: if a user fails to opt-in at one step, the user thinks that they're protected against tracking but are not, which gives them a false sense of security.
```

2022-01-07 16:42 UTC, Rob--W commented
@dotproto I've updated the source in Google Docs with your suggestions and exported again. The diff between your last review and the update is at https://github.com/w3c/webextensions/compare/07b3aa54cf7d71364498ab92af86984ca1e013e0..319add9a2932aef96e07b04ce45db3a73a4de4b0

(I've also included a link to Oliver's proposal in the doc for future reference).

2022-01-07 21:35 UTC, dotproto approved these changes
LGTM

2022-01-07 21:53 UTC, merged