Create initial deploy.yml
w3c/webextensions pull request #80
Opened 2021-09-15 21:52 UTC by mukul-p

Using SpecProd to verify the bikeshed file (https://w3c.github.io/spec-prod/)

2021-09-16 01:44 UTC, dotproto commented
@mukul-p, is deploy.yml meant to be used with Github Actions? If so, the [Actions reference docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows) state that workflows must be stored in the `.github/workflows/` directory.

2021-09-16 07:38 UTC, dotproto requested changes
In addition to my [last comment](https://github.com/w3c/webextensions/pull/80#issuecomment-920510027), I have a couple suggestions on how we might clean this file up a little.

2021-09-16 07:38 UTC, dotproto commented on deploy.yml
> +          # Deployment will be available at: https://<org>.github.io/<repo>/specification/
```suggestion
          # Deployment will be available at: https://w3c.github.io/webextensions/specification/
          DESTINATION: specification/index.html
```

Move the comment above the output destination and make the URL specific to our repo.

2021-09-16 07:38 UTC, dotproto commented on deploy.yml
> +          VALIDATE_MARKUP: true
```suggestion
```

I think we should either specify all args to be explicit or trust in the defaults provided with w3c/spec-prod@2. Since we have have not specified most flags, I'd suggest that we drop these ones as well.

2021-09-16 07:38 UTC, dotproto commented on deploy.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-20.04
```

I imagine using `ubuntu-latest` is probably fine, but since spec-prod [Getting started](https://w3c.github.io/spec-prod/#getting-started) instructions explicitly uses I'd suggest we follow their lead.

2021-09-16 07:38 UTC, dotproto commented on deploy.yml
> +    name: Build, Validate and Deploy
```suggestion
    name: Build, Validate, and Deploy
```

I'm a fan of the [serial comma](https://en.wikipedia.org/wiki/Serial_comma) ;)

2021-09-16 08:05 UTC, mukul-p commented
> @mukul-p, is deploy.yml meant to be used with Github Actions? If so, the [Actions reference docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows) state that workflows must be stored in the `.github/workflows/` directory.

Never trust the (Web) UI :). Use cmd-line or equivalent.

2021-09-20 21:21 UTC, dotproto approved these changes

2021-09-20 21:21 UTC, merged